CREATE TABLE IF NOT EXISTS TIPOS_JUZGADOS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    denominacion TEXT NOT NULL
);

INSERT INTO tipos_juzgados (denominacion) VALUES
('Tribunal Supremo'),
('Sala de lo Civil del Tribunal Supremo'),
('Sala de lo Penal del Tribunal Supremo'),
('Sala de lo Contencioso-Administrativo del Tribunal Supremo'),
('Sala de lo Social del Tribunal Supremo'),
('Sala de lo Militar del Tribunal Supremo'),
('Audiencia Nacional'),
('Sala de lo Penal de la Audiencia Nacional'),
('Sala de lo Contencioso-Administrativo de la Audiencia Nacional'),
('Sala de lo Social de la Audiencia Nacional'),
('Sección de Menores del Tribunal Central de Instancia'),
('Sección de Instrucción del Tribunal Central de Instancia'),
('Sección de lo Penal del Tribunal Central de Instancia'),
('Sección de lo Contencioso-Administrativo del Tribunal Central de Instancia'),
('Tribunal Superior de Justicia'),
('Sala de lo Civil y Penal del Tribunal Superior de Justicia'),
('Sala de lo Contencioso-Administrativo del Tribunal Superior de Justicia'),
('Sala de lo Social del Tribunal Superior de Justicia'),
('Audiencia Provincial'),
('Tribunal de Instancia'),
('Sección Civil y de Instrucción del Tribunal de Instancia'),
('Sección Civil del Tribunal de Instancia'),
('Sección de Instrucción del Tribunal de Instancia'),
('Sección de lo Social del Tribunal de Instancia'),
('Sección de lo Contencioso-Administrativo del Tribunal de Instancia'),
('Sección de lo Mercantil del Tribunal de Instancia'),
('Sección de Violencia sobre la Mujer del Tribunal de Instancia'),
('Sección de Violencia sobre la Infancia y la Adolescencia del Tribunal de Instancia'),
('Sección de Familia, Infancia y Capacidad del Tribunal de Instancia'),
('Sección de lo Penal del Tribunal de Instancia'),
('Sección de Vigilancia Penitenciaria del Tribunal de Instancia'),
('Sección de Menores del Tribunal de Instancia'),
('Registro Civil Central'),
('Registro Civil');
